version: '3.9'

services:
  postgres:
    image: postgres:16.1-alpine3.19
    container_name: postgres
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_DB=$DB_DBNAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    ports:
      - "$DB_PORT:$DB_PORT"
    volumes:
      - ./.private/data/postgres:/var/lib/postgresql/data
      - ./migrations/:/docker-entrypoint-initdb.d/
